# Generated by Django 4.0.5 on 2022-08-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Ammount', models.CharField(max_length=100)),
                ('Number', models.CharField(max_length=100)),
                ('User', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=100)),
                ('Ammount', models.CharField(max_length=100)),
                ('Class', models.CharField(max_length=100)),
                ('Image', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='login_info',
            old_name='Pass_word',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login_info',
            old_name='User_name_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='signup_info',
            old_name='Manager_Email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='signup_info',
            old_name='Imo_Number',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='signup_info',
            old_name='Manager_Contact',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='signup_info',
            old_name='Owner_Contact',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='signup_info',
            old_name='Pass_Name',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='signup_info',
            old_name='Port_of_Registery',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Owner_Email',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Use_Name',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Vessel_Manager',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Vessel_Name',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Vessel_Owner',
        ),
        migrations.RemoveField(
            model_name='signup_info',
            name='Vessel_Type',
        ),
    ]
