# Generated by Django 4.0.5 on 2022-08-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0002_admin_cart_info_contact_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_info',
            name='Description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='products',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
