# Generated by Django 4.0.5 on 2022-08-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0003_alter_cart_info_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Image',
            field=models.ImageField(upload_to=''),
        ),
    ]
