# Generated by Django 4.0.5 on 2022-08-09 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0009_signup_info_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup_info',
            name='Last_Name',
        ),
    ]
