# Generated by Django 4.0.5 on 2022-08-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0011_signup_info_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup_info',
            name='Img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
