# Generated by Django 3.2.3 on 2022-09-05 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Handler', '0013_auto_20220824_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_info',
            old_name='Number',
            new_name='Quantity',
        ),
    ]
